name: Bump mobile version

on:
  pull_request:
    types: [closed]
    branches:
      - master
      - feat/kmp-versioning
    paths:
      - 'mobile/kmp/**'

jobs:
  bump:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: gradle/actions/setup-gradle@v4

      - name: Bump version
        id: bump
        run: |
          cd mobile/kmp
          ./gradlew bumpVersion

      - name: Commit
        uses: atls/shared/.github/actions/github/commit/create@master
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          branchName: master
          commitMessage: "chore(common): version bump to ${{ steps.bump.outputs.version }}"
          workingDirectory: .
          filePattern: mobile/kmp/**
